project:
  type: website
  preview: 
    port: 3333

  render:
    # Render all .qmd files
    - "**/*.qmd"

execute:
  freeze: auto

website:
  title: "Mastering Conjoint Analysis"
  description: "Materials for course on conjoint analysis"
  site-url: "https://andrewheiss.github.io/mastering-conjoint-analysis_2026-06/"
  # favicon: 

  repo-url: "https://github.com/andrewheiss/mastering-conjoint-analysis_2026-06"
  repo-actions: [source, issue]

  draft-mode: visible

  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/andrewheiss/mastering-conjoint-analysis_2026-06

  sidebar:
    title: "Conjoints"
    style: docked
    background: secondary

    contents:
      - text: Home
        href: index.qmd
      
      - text: Setup
        href: "materials/setup/index.qmd"

      - section: "Materials"
        contents:
          - text: Introduction
            href: "materials/intro/index.qmd"
          
          - text: Designing conjoint experiments
            href: "materials/designing/index.qmd"
          
          - text: Implementing and fielding conjoint surveys
            href: "materials/implementing/index.qmd"
          
          - text: Causal inference analysis
            href: "materials/causal-inference/index.qmd"
          
          - text: Preference analysis
            href: "materials/preferences/index.qmd"

  page-footer:
    border: false
    background: "#e9ecef"
    left: |
      Content {{< fa brands creative-commons >}} 2026 by [Andrew Heiss](https://www.andrewheiss.com) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}}
      [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](hhttps://creativecommons.org/licenses/by-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/mastering-conjoint-analysis_2026-06)


format:
  html:
    highlight-style: github
    theme:
      - cosmo
      # - css/site-styles.scss
      - brand
    toc: true
