---
title: "Analyzing conjoint data for respondent preferences"
---

## Slides

No slides for this one!

## Exercises and materials

We'll be working through these things together:

- `03-1_preference-conjoints_exercise.qmd`
- `03-2_preferences-hierarchical-bayes.qmd`
- `03-3_shiny-example.qmd`
- `03-4_market-simulator.qmd`

Make sure you [grab the latest version of the workshop materials](https://github.com/andrewheiss/mastering-conjoint-analysis-materials_2026-06) first!

Download the pre-run Bayesian models:

- [`models.zip`](https://osf.io/k347f/files/osfstorage/6a21863dd477d86f790bd14b)

Unzip that file and put these:

- `model_brms_minivan_carpool.rds`
- `model_brms_minivan_hb.rds`
- `model_brms_minivan_wtp.rds`
- `model_brms_minivan.rds`

…in the `models/` folder in your project. This will make it so you don't have re-run the models on your computer.

## Crash course in Shiny

### General resources

- [Welcome to Shiny](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/)
- [Shiny components](https://shiny.posit.co/r/components/)
- [Shiny layouts](https://shiny.posit.co/r/layouts/)
- [{bslib}](https://rstudio.github.io/bslib/index.html)

### Shinylive

- [{shinylive}](https://posit-dev.github.io/r-shinylive/)
- [Shinylive examples](https://shinylive.io/r/examples/)
- [Shinylive Quarto extension](https://quarto-ext.github.io/shinylive/)
- [WebR](https://docs.r-wasm.org/webr/latest/) and [Quarto Live](https://r-wasm.github.io/quarto-live/)
- [webRios](https://webrios.caffeinatedmath.com/) and [webRoid](https://webroid.caffeinatedmath.com/)

### Publishing

- [Posit Connect Cloud](https://connect.posit.cloud/)

### Bare minimum app skeleton

```{.r}
library(shiny)
library(bslib)

# Define UI ----
ui <- page_sidebar(
 
)

# Define server logic ----
server <- function(input, output) {

}

# Run the app ----
shinyApp(ui = ui, server = server)
```
